security:
  oauth2:
    client:
      client-id: zb
      client_secret: zb
      access-token-uri: http://127.0.0.1:8000/server/oauth/token
      user-authorization-uri: http://127.0.0.1:8000/server/oauth/authorize
      registered-redirect-uri: http://127.0.0.1:8081/client2/index.html
    resource:
      jwt:
        key-uri: http://127.0.0.1:8000/server/oauth/token_key
server:
  port: 8081
  servlet:
    context-path: /client2